export const StoreSeed = [
  {
    name: "Recoger en Tienda Cumbres",
    is_open: true,
    latitude: 25.8322,
    longitude: -100.2978,
    address: "Ave. Paseo de los Leones No. 3399, Col. Cumbres",
    city: "Monterrey",
    state: "Nuevo Leon",
    country: "Mexico",
    created_at: `${new Date()}`,
    updated_at: `${new Date()}`,
  },
  {
    name: "Recoger en tienda Chipinque",
    is_open: true,
    latitude: 25.749346,
    longitude: -100.259866,
    address: "Ave. Gomez Morin #300, Col. del Valle",
    city: "Monterrey",
    state: "Nuevo Leon",
    country: "Mexico",
    created_at: `${new Date()}`,
    updated_at: `${new Date()}`,
  },
  {
    name: "Recoger en tienda Sendero",
    is_open: true,
    latitude: 25.871035,
    longitude: -100.17329,
    address: "Ave. Sendero Nte, Col #1001, Privadas de Anáhuac",
    city: "Monterrey",
    state: "Nuevo Leon",
    country: "Mexico",
    created_at: `${new Date()}`,
    updated_at: `${new Date()}`,
  },
  {
    name: "Recoger en tienda Contry",
    is_open: true,
    latitude: 25.7261055,
    longitude: -100.1750157,
    address: "Av. Eugenio Garza Sada 4321",
    city: "Monterrey",
    state: "Nuevo Leon",
    country: "Mexico",
    created_at: `${new Date()}`,
    updated_at: `${new Date()}`,
  },
  {
    name: "Domicilios desde Cumbres",
    is_open: true,
    latitude: 25.7322,
    longitude: -100.3978,
    address: "Ave. Paseo de los Leones No. 3399, Col. Cumbres",
    city: "Monterrey",
    state: "Nuevo Leon",
    country: "Mexico",
    created_at: `${new Date()}`,
    updated_at: `${new Date()}`,
  },
  {
    name: "Domicilios desde eFC Zona Valle",
    is_open: true,
    latitude: 25.6764098,
    longitude: -100.3733956,
    address: "AARON SAENZ 1717 COLONIA SANTA MARIA C.P.",
    city: "Monterrey",
    state: "Nuevo Leon",
    country: "Mexico",
    created_at: `${new Date()}`,
    updated_at: `${new Date()}`,
  },
  {
    name: "Domicilio desde Sendero",
    is_open: true,
    latitude: 25.771035,
    longitude: -100.27329,
    address: "Ave. Sendero Nte, Col #1001, Privadas de Anáhuac",
    city: "Monterrey",
    state: "Nuevo Leon",
    country: "Mexico",
    created_at: `${new Date()}`,
    updated_at: `${new Date()}`,
  },
  {
    name: "Domicilios desde Contry",
    is_open: true,
    latitude: 25.6261055,
    longitude: -100.2750157,
    address: "Av. Eugenio Garza Sada 4321",
    city: "Monterrey",
    state: "Nuevo Leon",
    country: "Mexico",
    created_at: `${new Date()}`,
    updated_at: `${new Date()}`,
  },
];
