version: 2.0
jobs:
  build:
    working_directory: ~/tmpbuild
    docker:
      - image: circleci/node:13.12.0
      - image: mongo:4.2.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run lint, tests, coverage
          name: test
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/junit
            JEST_JUNIT_OUTPUT_NAME: js-test-results.xml
          command: npm run ci:test -- --testResultsProcessor="jest-junit"
      - store_test_results:
            path: reports/junit
      - store_artifacts:
            path: reports/junit
